kind: "BuildConfig"

apiVersion: "v1"

metadata:

  name: "serenity-api-pipeline"

spec:

  strategy:

    jenkinsPipelineStrategy:

      jenkinsfilePath: "./Jenkinsfile"

      type: JenkinsPipeline
