kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "serenity-build-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: <pipeline content from below>
    type: JenkinsPipeline